## A component that indicates a building generates power.
class_name PowerGeneratorComponent
extends BuildingComponent

## Power generated, per units of power, per second.
@export
var power_generation: float

func get_kind() -> Kind:
    return Kind.POWER_GENERATOR

## Requests that a given delta time amount of energy be generated by this component.
func generate_power(delta: float) -> float:
    return power_generation * delta
